#!/bin/bash

# These dates are verified by HSKP data, only after the Garmin GPS acquires a sync. There may be data recorded prior to sync.
# Dont trust that data.

if [[ $# -lt 2 ]] || [[ $1 -gt 8 ]]; then
	echo "Usage: sys_loc [system number {0-6,8}] [YYYYMMDD]"
	echo "Output: Site [PG0-PG5, SP, VT, MCH]"
else
	indate=$(date -d $2 +%s)
	# echo $indate

	case $1 in
		"1" )
			echo "PG1"
			;;
		"2" )
			if [[ $indate -ge $(date -d "2009-01-08" +%s) ]] && [[ $indate -le $(date -d "2010-12-28" +%s) ]]; then
				echo "PG2"
			elif [[ $indate -ge $(date -d "2011-12-30" +%s) ]] && [[ $indate -le $(date -d "2011-12-31" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2013-07-19" +%s) ]] && [[ $indate -le $(date -d "2013-07-19" +%s) ]]; then
				echo "MCH"
			elif [[ $indate -ge $(date -d "2013-12-31" +%s) ]] && [[ $indate -le $(date -d "2014-12-11" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2014-12-28" +%s) ]]; then
				echo "PG0"
			else
				echo "NA"
			fi
			;;
		"3" ) # verified with HSKP by SEC
			if [[ $indate -ge $(date -d "2011-02-14" +%s) ]] && [[ $indate -le $(date -d "2011-12-20" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2012-01-09" +%s) ]] && [[ $indate -le $(date -d "2012-04-30" +%s) ]]; then
				echo "PG2"
			elif [[ $indate -ge $(date -d "2013-07-12" +%s) ]] && [[ $indate -le $(date -d "2013-07-19" +%s) ]]; then
				echo "MCH"
			elif [[ $indate -ge $(date -d "2013-12-29" +%s) ]] && [[ $indate -le $(date -d "2014-06-07" +%s) ]]; then
				echo "SP" 
			elif [[ $indate -ge $(date -d "2014-9-30" +%s) ]] && [[ $indate -le $(date -d "2014-10-06" +%s) ]]; then
				echo "MCH"
			elif [[ $indate -ge $(date -d "2014-10-24" +%s) ]] && [[ $indate -le $(date -d "2015-12-22" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2016-01-06" +%s) ]]; then
				echo "PG5"
			else
				echo "NA"
			fi
			;;
		"4" ) # verified with HSKP by SEC
			if [[ $indate -ge $(date -d "2011-02-14" +%s) ]] && [[ $indate -le $(date -d "2012-12-26" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2012-12-27" +%s) ]]; then
				echo "PG2" 
			else
				echo "NA"
			fi
			;;
		"5" ) # verified with HSKP by SEC
			if [[ $indate -ge $(date -d "2011-05-09" +%s) ]] && [[ $indate -le $(date -d "2011-07-04" +%s) ]]; then
				echo "VT"
			elif [[ $indate -ge $(date -d "2011-08-08" +%s) ]] && [[ $indate -le $(date -d "2012-08-09" +%s) ]]; then
				echo "MCH"
			elif [[ $indate -ge $(date -d "2011-09-07" +%s) ]] && [[ $indate -le $(date -d "2011-09-07" +%s) ]]; then
				echo "VT"
			elif [[ $indate -ge $(date -d "2011-12-26" +%s) ]] && [[ $indate -le $(date -d "2012-12-21" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2013-01-03" +%s) ]]; then
				echo "PG3"
			else
				echo "NA"
			fi
			;;
		"6" ) # verified with HSKP by SEC
			if [[ $indate -ge $(date -d "2011-02-11" +%s) ]] && [[ $indate -le $(date -d "2011-07-12" +%s) ]]; then
				echo "MCH"
			elif [[ $indate -ge $(date -d "2011-12-28" +%s) ]] && [[ $indate -lt $(date -d "2013-12-29" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2014-01-05" +%s) ]] && [[ $indate -lt $(date -d "2017-12-28" +%s) ]]; then
				echo "PG4"
			elif [[ $indate -ge $(date -d "2018-05-12" +%s) ]] && [[ $indate -lt $(date -d "2018-09-11" +%s) ]]; then
				echo "VT"
			elif [[ $indate -ge $(date -d "2019-01-10" +%s) ]]; then
				echo "PG4"
			else
				echo "NA"
			fi
			;;
		"8" )
			if [[ $indate -ge $(date -d "2017-12-01" +%s) ]] && [[ $indate -le $(date -d "2017-12-27" +%s) ]]; then
				echo "SP"
			elif [[ $indate -ge $(date -d "2017-12-28" +%s) ]] && [[ $indate -lt $(date -d "2019-01-09" +%s) ]]; then
				echo "PG4"
			else
				echo "NA"
			fi
			;;
		* )
			echo "Usage: sys_loc [system number {0-6,8}] [YYYYMMDD]"
			echo "Output: Site [PG0-PG5, SP, VT, MCH]"
	esac
fi

